name: Build

on:
  pull_request:
    branches: [ 'main*' ]

jobs:
  lint-misspell-sanitycheck:
    uses: ./.github/workflows/sanitycheck.yml

  detect-changes:
    runs-on: windows-latest
    outputs:
      changes: ${{ steps.changes.outputs.changes }}
    steps:
    - uses: AurorNZ/paths-filter@v3
      id: changes
      with:
        filters: |
          md: ['**.md']
          build: ['build/**', '.github/**/*.yml', '**/*.targets', '**/*.props']
          shared: ['src/Shared/**']
          code: ['**.cs', '.editorconfig']

  lint-md:
    needs: detect-changes
    if: contains(needs.detect-changes.outputs.changes, 'md')
    uses: ./.github/workflows/markdownlint.yml

  lint-dotnet-format:
    needs: detect-changes
    if: contains(needs.detect-changes.outputs.changes, 'code')
    uses: ./.github/workflows/dotnet-format.yml

  build-test-solution-stable:
    needs: detect-changes
    if: |
      contains(needs.detect-changes.outputs.changes, 'code')
      || contains(needs.detect-changes.outputs.changes, 'build')
      || contains(needs.detect-changes.outputs.changes, 'shared')

    strategy:
      fail-fast: false  # ensures the entire test matrix is run, even if one permutation fails
      matrix:
        os: [ windows-latest, ubuntu-latest ]
        version: [ net462, net6.0, net7.0, net8.0 ]
        exclude:
        - os: ubuntu-latest
          version: net462

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0 # fetching all

    - name: Setup dotnet
      uses: actions/setup-dotnet@v3

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore --property:ExposeExperimentalFeatures=false

    - name: Test ${{ matrix.version }}
      run: dotnet test **/bin/**/${{ matrix.version }}/*.Tests.dll --logger:"console;verbosity=detailed"

  build-test-solution-experimental:
    needs: detect-changes
    if: |
      contains(needs.detect-changes.outputs.changes, 'code')
      || contains(needs.detect-changes.outputs.changes, 'build')
      || contains(needs.detect-changes.outputs.changes, 'shared')

    strategy:
      fail-fast: false  # ensures the entire test matrix is run, even if one permutation fails
      matrix:
        os: [ windows-latest, ubuntu-latest ]
        version: [ net462, net6.0, net7.0, net8.0 ]
        exclude:
        - os: ubuntu-latest
          version: net462

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0 # fetching all

    - name: Setup dotnet
      uses: actions/setup-dotnet@v3

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore --property:ExposeExperimentalFeatures=true

    - name: Test ${{ matrix.version }}
      run: dotnet test **/bin/**/${{ matrix.version }}/*.Tests.dll --logger:"console;verbosity=detailed"

  build-test:
    needs: [
      lint-misspell-sanitycheck,
      detect-changes,
      lint-md,
      lint-dotnet-format,
      build-test-solution-stable,
      build-test-solution-experimental,
      ]
    if: always() && !cancelled() && !contains(needs.*.result, 'failure')
    runs-on: windows-latest
    steps:
    - run: echo 'build complete ✓'
