name: Lint - dotnet format

on:
  workflow_call:

jobs:
  run-dotnet-format:
    runs-on: windows-latest

    steps:
    - name: check out code
      uses: actions/checkout@v4

    - name: Setup dotnet
      uses: actions/setup-dotnet@v3

    - name: Install dotnet-format
      run: dotnet tool install -g dotnet-format

    - name: dotnet format
      run: dotnet-format --folder --check
