name: Integration Tests

on:
  workflow_call:

jobs:
  run-w3c-trace-context-integration-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: [ net6.0, net7.0 ]
    steps:
      - uses: actions/checkout@v4

      - name: Run W3C Trace Context docker-compose
        run: docker-compose --file=test/OpenTelemetry.Instrumentation.W3cTraceContext.Tests/docker-compose.yml --file=build/docker-compose.${{ matrix.version }}.yml --project-directory=. up --exit-code-from=tests --build

  run-otlp-exporter-integration-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: [ net6.0, net7.0, net8.0 ]
    steps:
      - uses: actions/checkout@v4

      - name: Run OTLP Exporter docker-compose
        run: docker-compose --file=test/OpenTelemetry.Exporter.OpenTelemetryProtocol.Tests/IntegrationTest/docker-compose.yml --file=build/docker-compose.${{ matrix.version }}.yml --project-directory=. up --exit-code-from=tests --build
